"""add incident analysis data

Revision ID: 28c50cd1258a
Revises: 192690d58087
Create Date: 2026-08-12 04:29:37.346580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c50cd1258a'
down_revision: Union[str, Sequence[str], None] = '192690d58087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('iocs', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('threats', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('mitre', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('recommendations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'recommendations')
    op.drop_column('incidents', 'mitre')
    op.drop_column('incidents', 'threats')
    op.drop_column('incidents', 'iocs')
    # ### end Alembic commands ###
