"""add risk score to incidents

Revision ID: 72a3b0ebfcd8
Revises: 28c50cd1258a
Create Date: 2026-08-17 15:09:38.033057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a3b0ebfcd8'
down_revision: Union[str, Sequence[str], None] = '28c50cd1258a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('risk_score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'risk_score')
    # ### end Alembic commands ###
